rm -Rf .output/
rm -Rf driver/.output/
rm -Rf libc/.output/
rm -Rf lua/.output/
rm -Rf platform/.output/
rm -Rf modules/.output/
rm -Rf spiffs/.output/
rm -Rf apps/wifikiller/.output/
rm -Rf apps/luaapp/.output/