rm -Rf .output
rm -Rf driver/.output
rm -Rf mylibc/.output
rm -Rf lua/.output
rm -Rf platform/.output
rm -Rf modules/.output
rm -Rf spiffs/.output
rm -Rf cjson/.output
rm -Rf coap/.output
rm -Rf lpeg/.output
rm -Rf apps/luaapp/.output
rm -Rf apps/task/.output
rm -Rf apps/wifikiller/.output
