#define GPIO_GPIO_PIN0_INT_ENA 0x0000001F
#define GPIO_GPIO_PIN0_INT_ENA_S 13
#define GPIO_GPIO_PIN0_PAD_DRIVER (BIT(2))

#define GPIO_PIN_INT_TYPE_LSB			7
#define GPIO_PIN_INT_TYPE_MASK			0x380

#define GPIO_OUT_W1TS (DR_REG_GPIO_BASE + 0x0008)
#define GPIO_OUT_W1TC (DR_REG_GPIO_BASE + 0x000c)
#define GPIO_ENABLE_W1TC (DR_REG_GPIO_BASE + 0x0028)
#define GPIO_ENABLE_W1TS (DR_REG_GPIO_BASE + 0x0024)
#define GPIO_OUT1_W1TS (DR_REG_GPIO_BASE + 0x0014)
#define GPIO_OUT1_W1TC (DR_REG_GPIO_BASE + 0x0018)
#define GPIO_ENABLE1_W1TS (DR_REG_GPIO_BASE + 0x0030)
#define GPIO_ENABLE1_W1TC (DR_REG_GPIO_BASE + 0x0034)
#define GPIO_IN (DR_REG_GPIO_BASE + 0x003c)
#define GPIO_IN1 (DR_REG_GPIO_BASE + 0x0040)

#define GPIO_PIN_PAD_DRIVER_LSB			2
#define GPIO_PIN_PAD_DRIVER_MASK		0x00000004
#define GPIO_PIN_PAD_DRIVER_SET(x)		(((x) << GPIO_PIN_PAD_DRIVER_LSB) & GPIO_PIN_PAD_DRIVER_MASK)
#define GPIO_PAD_DRIVER_ENABLE			1