#ifndef _GPIO_SD_REG_EXT_H_
#define _GPIO_SD_REG_EXT_H_

#define SIGMADELTA0 (DR_REG_GPIO_SD_BASE + 0x0000)
#define SIGMADELTA_SD0_PRESCALE 0x000000FF
#define SIGMADELTA_SD0_PRESCALE_S 8

#endif